import Head from 'next/head'
import { Button } from '@mui/material'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { Suspense, useEffect, useState } from 'react'

const ClientDynamicComponent = dynamic(() => import('../components/TestComponent'))

export default function Home() {
  const [showComponent, setShowComponent] = useState(false)

  useEffect(() => {
    setTimeout(() => {
      setShowComponent(true)
    }, 2000)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Button
          size='medium'
          color='primary'
          variant='contained'
        >
          Testing
        </Button>

        <Link href='/baz' target='_blank'>
          This is a link
        </Link>

        {
          showComponent ? <Suspense>
            <ClientDynamicComponent />
          </Suspense> : null
        }
      </div>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: {}
  }
}